CREATE TABLE `financing_simulations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`propertyType` varchar(100),
	`desiredLocation` varchar(255),
	`estimatedValue` int,
	`propertyValue` int NOT NULL,
	`downPayment` int NOT NULL,
	`financedAmount` int NOT NULL,
	`termMonths` int NOT NULL,
	`amortizationSystem` enum('SAC','PRICE') NOT NULL DEFAULT 'SAC',
	`selectedBank` varchar(100),
	`interestRate` decimal(5,2),
	`firstInstallment` int,
	`lastInstallment` int,
	`averageInstallment` int,
	`totalAmount` int,
	`totalInterest` int,
	`ipAddress` varchar(45),
	`userAgent` text,
	`status` enum('pending','contacted','converted','lost') DEFAULT 'pending',
	`contacted` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financing_simulations_id` PRIMARY KEY(`id`)
);
