CREATE TABLE `landlord_transfers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`landlordId` int NOT NULL,
	`referenceMonth` varchar(7) NOT NULL,
	`totalRentReceived` int NOT NULL,
	`totalCommissions` int NOT NULL,
	`totalExpenses` int NOT NULL,
	`netAmount` int NOT NULL,
	`paymentsIncluded` text,
	`expensesIncluded` text,
	`transferDate` date,
	`transferMethod` varchar(50),
	`transferProof` varchar(500),
	`status` enum('pendente','processando','concluido','cancelado') NOT NULL DEFAULT 'pendente',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `landlord_transfers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `landlords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`cpfCnpj` varchar(20) NOT NULL,
	`rg` varchar(20),
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`whatsapp` varchar(20),
	`address` varchar(255),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(10),
	`bankName` varchar(100),
	`bankCode` varchar(10),
	`agencyNumber` varchar(20),
	`accountNumber` varchar(20),
	`accountType` enum('corrente','poupanca'),
	`pixKey` varchar(255),
	`pixKeyType` enum('cpf','cnpj','email','telefone','aleatoria'),
	`commissionRate` decimal(5,2) DEFAULT '10.00',
	`autoTransfer` boolean DEFAULT false,
	`status` enum('ativo','inativo','bloqueado') NOT NULL DEFAULT 'ativo',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `landlords_id` PRIMARY KEY(`id`),
	CONSTRAINT `landlords_cpfCnpj_unique` UNIQUE(`cpfCnpj`)
);
--> statement-breakpoint
CREATE TABLE `property_expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`landlordId` int NOT NULL,
	`contractId` int,
	`expenseType` enum('manutencao','reparo','pintura','limpeza','jardinagem','seguranca','seguro','iptu','condominio','taxa_administracao','outros') NOT NULL,
	`description` text NOT NULL,
	`amount` int NOT NULL,
	`paidBy` enum('imobiliaria','proprietario','inquilino') NOT NULL,
	`expenseDate` date NOT NULL,
	`paymentDate` date,
	`status` enum('pendente','pago','reembolsado') NOT NULL DEFAULT 'pendente',
	`receiptUrl` varchar(500),
	`invoiceNumber` varchar(100),
	`supplierName` varchar(255),
	`supplierCpfCnpj` varchar(20),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `property_expenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rent_adjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`previousAmount` int NOT NULL,
	`newAmount` int NOT NULL,
	`adjustmentPercentage` decimal(5,2) NOT NULL,
	`adjustmentIndex` varchar(50) NOT NULL,
	`indexValue` decimal(8,4) NOT NULL,
	`effectiveDate` date NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rent_adjustments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`landlordId` int NOT NULL,
	`tenantId` int NOT NULL,
	`contractNumber` varchar(50),
	`startDate` date NOT NULL,
	`endDate` date NOT NULL,
	`durationMonths` int NOT NULL,
	`rentAmount` int NOT NULL,
	`condoFee` int DEFAULT 0,
	`iptu` int DEFAULT 0,
	`waterBill` int DEFAULT 0,
	`gasBill` int DEFAULT 0,
	`condoFeeResponsibility` enum('proprietario','inquilino') DEFAULT 'inquilino',
	`iptuResponsibility` enum('proprietario','inquilino') DEFAULT 'proprietario',
	`commissionRate` decimal(5,2) NOT NULL,
	`commissionAmount` int NOT NULL,
	`paymentDay` int NOT NULL DEFAULT 5,
	`depositAmount` int,
	`guarantorName` varchar(255),
	`guarantorCpf` varchar(14),
	`guarantorPhone` varchar(20),
	`adjustmentIndex` enum('IGPM','IPCA','INPC') DEFAULT 'IGPM',
	`lastAdjustmentDate` date,
	`status` enum('ativo','encerrado','suspenso') NOT NULL DEFAULT 'ativo',
	`contractUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_contracts_id` PRIMARY KEY(`id`),
	CONSTRAINT `rental_contracts_contractNumber_unique` UNIQUE(`contractNumber`)
);
--> statement-breakpoint
CREATE TABLE `rental_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`propertyId` int NOT NULL,
	`landlordId` int NOT NULL,
	`tenantId` int NOT NULL,
	`referenceMonth` varchar(7) NOT NULL,
	`rentAmount` int NOT NULL,
	`condoFee` int DEFAULT 0,
	`iptu` int DEFAULT 0,
	`waterBill` int DEFAULT 0,
	`gasBill` int DEFAULT 0,
	`otherCharges` int DEFAULT 0,
	`totalAmount` int NOT NULL,
	`lateFee` int DEFAULT 0,
	`interest` int DEFAULT 0,
	`discount` int DEFAULT 0,
	`commissionRate` decimal(5,2) NOT NULL,
	`commissionAmount` int NOT NULL,
	`landlordAmount` int NOT NULL,
	`dueDate` date NOT NULL,
	`paymentDate` date,
	`status` enum('pendente','pago','atrasado','cancelado') NOT NULL DEFAULT 'pendente',
	`paymentMethod` varchar(50),
	`paymentProof` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tenants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20),
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`whatsapp` varchar(20),
	`occupation` varchar(100),
	`employer` varchar(255),
	`monthlyIncome` int,
	`emergencyContact` varchar(255),
	`emergencyPhone` varchar(20),
	`status` enum('ativo','inativo') NOT NULL DEFAULT 'ativo',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tenants_id` PRIMARY KEY(`id`),
	CONSTRAINT `tenants_cpf_unique` UNIQUE(`cpf`)
);
