export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  n8nLeadWebhookUrl: process.env.N8N_LEAD_WEBHOOK_URL ?? "",
  n8nChatWebhookUrl: process.env.VITE_N8N_CHAT_WEBHOOK_URL ?? "",
  storageBucket: process.env.STORAGE_BUCKET ?? "",
  storageRegion: process.env.STORAGE_REGION ?? "",
  storageEndpoint: process.env.STORAGE_ENDPOINT ?? "",
  storageAccessKey: process.env.STORAGE_ACCESS_KEY ?? "",
  storageSecretKey: process.env.STORAGE_SECRET_KEY ?? "",
};
